Changed to register in postgreSQL
awakia/slack-exporter pull request #1
Opened 2023-05-14 16:12 UTC by imokenpi2011

## 変わったこと
* slackのメッセージをcsv出力ではなくPostgreSQLの登録に変更

## テストしたこと
* render.conに立てたインスタンスに対して登録が完了することを確認しました
  * DBを確認し、Asia/Tokyoのタイムゾーンで登録されていることを確認
  * コンフリクトしたデータを登録しようとした場合に登録がスキップされることを確認
    * (主キーの設定ミスで登録されるべきデータがスキップされるとかはないはず..)

## その他
* CSVの登録処理をそのまま変更したのでreactionsとmessagesを繋ぐ主キーがありません。場合によってはslack_messagesの中にJSON型でreactionsを格納してもいいと思いました。
* 今はチャンネル名をそのままslack_messagesに格納していますが、チャンネル名は変わる可能性が高いです。そのため、channel_idとチャンネル名のマッピングテーブルを作成し、実行のたびにUPSERTしてもいいと思いました。

2023-05-14 16:16 UTC, imokenpi2011 commented on main.py
> +                """)
slack_messagesとslack_reactionsの2テーブルに分けてみました。
ただ、2つを紐づけるような主キーがないのでアイデアあれば教えていただきたいです。

2023-05-14 16:16 UTC, imokenpi2011 commented on main.py
> +                query = f"INSERT INTO slack_reactions (channel_id, channel_name, ts, user_id, reaction_name, reaction_count, reaction_user) VALUES %s ON CONFLICT DO NOTHING;;"
`ON CONFLICT DO NOTHING;`を使用して主キーが被ってもスキップしてエラーにならない様にしました。
実際に動かす場合は取得日付を分けるので被ることはないと思います

2023-05-14 16:17 UTC, imokenpi2011 commented on main.py
> +    reactions: list[Reaction] = field(default_factory=list)
Chat GPTに相談しながらDBに登録しやすいよう定義を変えています

2023-05-15 01:20 UTC, awakia commented on main.py
> +    reactions: list[Reaction] = field(default_factory=list)
なるほど。こんな書き方あったのか。

2023-05-15 01:23 UTC, awakia commented on .env.sample
> +DB_PASS=
DATABASE_URL使った方が良い気がします。

`psycopg2.connect(DATABASE_URL)` でいけるっぽいし。
https://amateur-engineer-blog.com/heroku-postgres-connecting-by-python/

2023-05-15 01:34 UTC, awakia requested changes
DBの設計は直せないので、とりあえず普通に綺麗にするといいと思いました。
ChannelとUserのテーブルも作って、必要な時はその名前とJoinする方がいいかなと。

あとは元の機能は残して欲しかったのでそこは残しておいた方が幸せな気がします。
実行時にプラスで引数与える形でいいと思うので。

2023-05-15 01:34 UTC, awakia commented on main.py
> +                """)
slack_messagesは
channel_id, tsでUniqueなのでそこが主キーになるはずです。
ChannelNameはDBにする際には取ってしまってもいいと思ってます。

2023-05-15 01:34 UTC, awakia commented on main.py
> +    bot.export_data_worker(start_time, end_time)
export_data_to_csvは残したままではなぜダメだったのでしょうか？
一応今だとまたデータ取るときにうまくいくのに、これを変えるとちゃんと移行が済むまでデータ入れられなくなっちゃうと思います。
関数増やす形で対応できなかったのでしょうか？

2023-05-15 01:34 UTC, awakia commented on main.py
> +                        user_id VARCHAR(20) NOT NULL,
なので、ここのchannel_name, user_idはいらないと言えばいらない。まぁ誰への返信やリアクションなのかを解析しやすいので、user_idは残しておいてもいいけど、reaction_userとの整合性の問題で、
message_user, reaction_userか message_user_id, reaction_user_id のどちらかにする方がいいかもですね。
元のCSVの時からなんとかしろという話ですが、いろいろ制約があって変えられなかったけど今回は揃えていい気がします。

2023-05-15 01:34 UTC, awakia commented on main.py
> +                        user_id VARCHAR(20) NOT NULL,
下をreaction_userにするならここはuser

2023-05-15 01:34 UTC, awakia commented on main.py
> +    bot.export_data_worker(start_time, end_time)
export_data_workerという意味自体がよくわからないのですが、良い名前考えられないですか？
これをどういうふうに実行しようとしているかわかれば僕ももう少し考えられるかも。

2023-05-15 14:57 UTC, imokenpi2011 commented on main.py
> +    bot.export_data_worker(start_time, end_time)
ea5d38add66e23ce2fa18ff0f9e284c3e4d51727 でコマンドライン引数で処理を分岐できるよう変更しました！

関数名も`export_data_to_csv `と`export_data_to_ database`にし、処理内容をわかりやすく修正しました

2023-05-15 15:00 UTC, imokenpi2011 commented on main.py
> +                        user_id VARCHAR(20) NOT NULL,
userがPostgreSQLの予約語になっているので設定できなかったんですよね...
https://www.postgresql.jp/document/8.3/html/sql-keywords-appendix.html

`reaction_user `を`reaction_user _id`に変更します

2023-05-15 16:02 UTC, imokenpi2011 commented on .env.sample
> +DB_PASS=
変更しました！READMEにも記載してあります

2023-05-15 16:06 UTC, imokenpi2011 commented on main.py
> +                        user_id VARCHAR(20) NOT NULL,
https://github.com/awakia/slack-exporter/blob/e19187e0197f4d154c2f9a953d26277f00f461dc/main.py#L141-L146
`slack_channels`というテーブルを作成し、messagesとreactionsから`channel_name`の項目を削除しました。(csvの場合は含まれたままです)

https://github.com/awakia/slack-exporter/blob/e19187e0197f4d154c2f9a953d26277f00f461dc/main.py#L188
SQLとしてはデータがない場合はINSERT、存在する場合はchannel_nameに変更がある場合のみUPDATEをかける様にしています

2023-05-15 16:08 UTC, imokenpi2011 commented on main.py
> +                """)
slack_messagesの主キーをchannel_id, tsに変更しました。(reactionsはリアクション内容とユーザーIDを含めて初めて一意になるので変更していません)

下記のコメントでも記載した通り、ChannelNameは別テーブルに切り分けました
https://github.com/awakia/slack-exporter/pull/1#discussion_r1194052327

2023-05-16 04:49 UTC, awakia commented on main.py
> +                        channel_name VARCHAR(20) NOT NULL,
若干20で良いのかが不安です。varcharってbyte数だから、10文字とかだよね？

2023-05-16 04:50 UTC, awakia commented on main.py
> +    if len(sys.argv) != 2:
argparserとかなんか使おうw
ChatGPTに聞いてくれw

2023-05-16 05:08 UTC, awakia commented on main.py
> +def write_channel_data_for_database(message_data, channel_list):
てか、ORM使ってなかったんだね。使った方がいい気がするけど。

```
from dataclasses import dataclass
from typing import List
from sqlalchemy import Column, Integer, String, create_engine, ForeignKey
from sqlalchemy.orm import relationship

engine = create_engine('postgresql://user:password@localhost/dbname')

@dataclass
class Reaction:
    __tablename__ = 'reactions'
    __table_args__ = {'extend_existing': True}
    __metadata__ = engine

    id: int = Column(Integer, primary_key=True)
    name: str = Column(String)
    count: int = Column(Integer)
    users: List[str] = Column(String)  # You may need to handle this list of users differently
    message_id: int = Column(Integer, ForeignKey('messages.id'))

@dataclass
class Message:
    __tablename__ = 'messages'
    __table_args__ = {'extend_existing': True}
    __metadata__ = engine

    id: int = Column(Integer, primary_key=True)
    channel_id: str = Column(String)
    channel_name: str = Column(String)
    ts: str = Column(String)
    user: str = Column(String)
    text: str = Column(String)
    thread_ts: str = Column(String)
    reply_count: int = Column(Integer)
    reactions: List[Reaction] = relationship("Reaction", backref="message")
 ```
 
 ChatGPTに聞いたらSQLAlchemy使えと言われた。動くかは知らない

2023-05-16 05:10 UTC, awakia commented on main.py
> +def write_channel_data_for_database(message_data, channel_list):
一応ここで思ったこととしては、モデル(dataclasses)とSQLのテーブルは１対１対応してた方がいい気はするから、ここで処理し直してDBに入れるよりは、DBに入れられる形でデータを持ち回る方がいいだろうなぁみたいな。

2023-05-16 05:10 UTC, awakia requested changes
ごめん、すげぇ基礎的なことが見れてなかった＞＜

2023-05-16 05:10 UTC, awakia requested changes
ごめん、すげぇ基礎的なことが見れてなかった＞＜

2023-05-16 16:26 UTC, imokenpi2011 commented on main.py
> +                        channel_name VARCHAR(20) NOT NULL,
チャンネル名は80文字までだったので修正します....

2023-05-16 17:32 UTC, imokenpi2011 commented on main.py
> +def write_channel_data_for_database(message_data, channel_list):
f28992771fb03f963e55d0dd4c2cd854ef481fd5 にてSQLAlchemyを使用するようリファクタをかけました。
csv出力にはチャンネル名を入れ、DB書き込みはチャンネル名を別テーブルに切り分けるようにしたかったので少しデータの持ち方に不安があります...

一応GPTのアドバイスを受けつつリファクタしています

2023-05-16 17:33 UTC, imokenpi2011 commented on main.py
> +    if len(sys.argv) != 2:
0bc65583a4461d5b0827ae8e286a704f10e91b1f にてargparseを使用するようリファクタをかけました。
この様なイメージで合っていますでしょうか？

2023-05-17 01:22 UTC, awakia commented on main.py
> +from psycopg2 import extras
ここらへんってまだ必要？

2023-05-17 01:24 UTC, awakia approved these changes
若干いらないImportとかある気がしたけどいい気がしました。

このモデルがある前提で、dataclassのMessage, Reactionもいらなくなる気もしたけれど、一旦このくらいでマージしてもいいと思います。

2023-05-17 01:24 UTC, awakia approved these changes
若干いらないImportとかある気がしたけどいい気がしました。

このモデルがある前提で、dataclassのMessage, Reactionもいらなくなる気もしたけれど、一旦このくらいでマージしてもいいと思います。

2023-05-17 01:25 UTC, awakia commented
なぜか毎回コメントが2回分入るのはなんのバグなんだろうw

2023-05-17 02:10 UTC, merged